// Autonomous AI Document Classifier & Project Routing Engine

/**
 * Autonomous Classifier Function
 * Analyzes incoming drawing title block, file metadata, or OCR text snippet.
 * Returns: { matchedProjectId, isNewProject, confidenceScore, parsedMetadata, autoGeneratedProject }
 */
export function classifyIncomingDrawing(filename = "", fileSnippet = "", activeProjects = []) {
  const combinedText = (filename + " " + fileSnippet).toLowerCase();

  // Pattern detection rules
  const detectedLocation = detectLocation(combinedText);
  const detectedClient = detectClient(combinedText);
  const detectedType = detectBuildingType(combinedText);

  // 1. Try matching against existing active projects
  let bestMatch = null;
  let highestScore = 0;

  activeProjects.forEach(proj => {
    let score = 0;
    const projTitle = proj.title.toLowerCase();
    const projClient = proj.client.toLowerCase();
    const projLoc = (proj.location || "").toLowerCase();

    if (detectedClient && projClient.includes(detectedClient.toLowerCase())) score += 40;
    if (detectedLocation && projLoc.includes(detectedLocation.toLowerCase())) score += 40;
    if (detectedType && proj.buildingType.toLowerCase().includes(detectedType.toLowerCase())) score += 20;

    // Direct filename keyword match
    if (filename && projTitle.split(' ').some(w => w.length > 3 && filename.toLowerCase().includes(w))) {
      score += 25;
    }

    if (score > highestScore) {
      highestScore = score;
      bestMatch = proj;
    }
  });

  // If match confidence >= 60%, assign to existing project
  if (bestMatch && highestScore >= 60) {
    return {
      isNewProject: false,
      matchedProjectId: bestMatch.id,
      matchedProjectTitle: bestMatch.title,
      confidenceScore: Math.min(highestScore + 15, 99),
      parsedMetadata: {
        location: detectedLocation || bestMatch.location,
        client: detectedClient || bestMatch.client,
        buildingType: detectedType || bestMatch.buildingType
      },
      reasoning: `Matched existing project '${bestMatch.title}' based on client tag (${detectedClient || 'Brand'}), location (${detectedLocation || 'City'}), and drawing title block.`
    };
  }

  // 2. Otherwise, automatically instantiate a new project
  const autoTitle = `${detectedClient || 'Client'} - ${detectedType || 'Structural Building'} (${detectedLocation || 'Site'})`;
  const newProjId = `proj-auto-${Date.now().toString().slice(-4)}`;

  const autoGeneratedProject = {
    id: newProjId,
    title: autoTitle,
    client: detectedClient ? `${detectedClient} Infrastructure` : "Incoming Client Direct",
    buildingType: detectedType || "Commercial Structural Frame",
    location: detectedLocation || "India Project Site",
    stories: detectedType?.includes('Warehouse') ? 1 : 5,
    designCode: detectedLocation?.includes('Andaman') ? "IS 800:2007 / IS 875 Wind 55m/s" : "IS 456 / IS 1893:2016",
    seismicZone: detectedLocation?.includes('Andaman') ? "Zone V (Z = 0.36 High Seismic)" : "Zone IV (Z = 0.24)",
    windSpeed: detectedLocation?.includes('Andaman') ? "55 m/s Cyclone Zone" : "47 m/s",
    soilBearingCapacity: "180 kN/m²",
    concreteGrade: "M30",
    steelGrade: "Fe500D TMT",
    stage: "concept",
    clientBrief: {
      image: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80",
      videoUrl: "",
      description: `Auto-ingested drawing file '${filename}'. AI parsed location: ${detectedLocation || 'Unknown'}, Client: ${detectedClient || 'Unknown'}, Building Typology: ${detectedType || 'Structural Frame'}.`,
      keyRequirements: [
        `Auto-extracted title block: ${filename}`,
        `Location: ${detectedLocation || 'Project Site'}`,
        `Autonomous routing: Created new pipeline card`
      ]
    },
    architecturalSpecs: {
      totalAreaSqFt: 22000,
      footprintDim: "20.0m x 18.0m",
      roomSchedule: [{ name: "Main Floor", dim: "20.0m x 18.0m" }]
    },
    structuralSpecs: {
      columnSizes: [{ id: "C1", dim: "450mm x 450mm", location: "Main Grid", rebar: "10 - 25mm dia" }],
      beamSizes: [{ id: "B1", dim: "300mm x 450mm", type: "Main Beam", rebar: "Top 3-16#, Bottom 4-20#" }],
      slabThickness: "150mm RCC Slab",
      foundationType: "Isolated RCC Footing",
      shearWallThickness: "200mm RCC Core Wall"
    },
    feaResults: {
      maxBendingMoment: "150 kN·m",
      maxShearForce: "90 kN",
      maxAxialLoad: "1900 kN",
      maxStoryDrift: "0.0018",
      maxDeflection: "10.2 mm",
      dcRatios: [{ member: "Column C1 Ground", ratio: 0.81, status: "PASS (Optimal)" }]
    },
    agentOutputs: {
      architect: { completed: true, timestamp: new Date().toLocaleTimeString(), summary: "Auto-instantiated project from intake drawing." },
      civil: { completed: false, timestamp: "", summary: "Pending BOQ calculation..." },
      draftsman: { completed: false, timestamp: "", summary: "Pending DXF & Tekla BIM..." },
      structural: { completed: false, timestamp: "", summary: "Pending ETABS & STAAD..." }
    },
    engineerApproval: { approved: false, signedBy: "", licenseNo: "", comments: "", approvalDate: "" }
  };

  return {
    isNewProject: true,
    matchedProjectId: newProjId,
    matchedProjectTitle: autoTitle,
    confidenceScore: 92,
    parsedMetadata: {
      location: detectedLocation || "Site Unspecified",
      client: detectedClient || "Client Unspecified",
      buildingType: detectedType || "Structural Building"
    },
    autoGeneratedProject,
    reasoning: `Drawing title block contains unrecognized project signature -> Automatically instantiated new pipeline project card '${autoTitle}'.`
  };
}

// Sub-parsers
function detectLocation(text) {
  if (text.includes('gurugram') || text.includes('gurgaon') || text.includes('mg road')) return "Gurugram, Haryana";
  if (text.includes('andaman') || text.includes('nicobar') || text.includes('port blair')) return "Port Blair, Andaman & Nicobar";
  if (text.includes('noida') || text.includes('sector 62')) return "Noida, UP";
  if (text.includes('mumbai') || text.includes('bandra')) return "Mumbai, Maharashtra";
  if (text.includes('bangalore') || text.includes('bengaluru')) return "Bengaluru, Karnataka";
  return null;
}

function detectClient(text) {
  if (text.includes('tanishq') || text.includes('titan')) return "Tanishq Retail";
  if (text.includes('nestle') || text.includes('amul')) return "Nestle & Amul Logistics";
  if (text.includes('metro housing') || text.includes('skyline')) return "Metro Housing";
  if (text.includes('vanguard')) return "Vanguard Commercial";
  return null;
}

function detectBuildingType(text) {
  if (text.includes('warehouse') || text.includes('cold storage') || text.includes('truss') || text.includes('fmcd')) return "Industrial Steel Cold Storage Warehouse";
  if (text.includes('tanishq') || text.includes('retail') || text.includes('showroom') || text.includes('cantilever')) return "Commercial Retail Cantilever RCC Frame";
  if (text.includes('apartment') || text.includes('residential') || text.includes('g+5')) return "Residential RCC Building";
  return null;
}
