import React, { useState } from 'react';
import { classifyIncomingDrawing } from '../services/projectAutoClassifier';

export default function AutonomousIntakeWatcher({ projects, onRouteFileToProject }) {
  const [dragActive, setDragActive] = useState(false);
  const [latestClassification, setLatestClassification] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);

  // Preset test sample drawing files for demonstration
  const sampleDrawingFiles = [
    {
      filename: "Tanishq_Gurugram_MG_Road_Structural_Cantilever_Rev4.dxf",
      snippet: "TITLE BLOCK: Tanishq Flagship Jewelry Showroom | Location: MG Road, Gurugram, Haryana | Cantilever Beam CANT1 M35",
      description: "Gurugram Tanishq Retail Showroom Drawing"
    },
    {
      filename: "Nestle_Amul_Port_Blair_Cold_Storage_Cyclone_Truss_Rev2.std",
      snippet: "TITLE BLOCK: Nestle India & Amul Cold Storage Depot | Location: Port Blair, Andaman & Nicobar Islands | 36m Span Portal Truss 55 m/s Wind",
      description: "Andaman & Nicobar Nestle & Amul Warehouse Drawing"
    },
    {
      filename: "Unassigned_New_Hotel_Resort_Bandra_Mumbai_Structural.dwg",
      snippet: "TITLE BLOCK: Luxury Sea-View Resort Tower | Location: Bandra West, Mumbai, Maharashtra | G+14 RCC Frame Shear Core",
      description: "Brand New Unassigned Project Drawing"
    }
  ];

  const handleProcessFile = (fileObj) => {
    setIsProcessing(true);
    setTimeout(() => {
      const result = classifyIncomingDrawing(fileObj.filename, fileObj.snippet, projects);
      setLatestClassification({
        filename: fileObj.filename,
        ...result
      });
      setIsProcessing(false);
    }, 600);
  };

  const handleRouteToProject = () => {
    if (!latestClassification) return;
    if (latestClassification.isNewProject && latestClassification.autoGeneratedProject) {
      onRouteFileToProject(latestClassification.autoGeneratedProject, true);
    } else {
      const existing = projects.find(p => p.id === latestClassification.matchedProjectId);
      if (existing) {
        onRouteFileToProject(existing, false);
      }
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl">
      <div className="flex justify-between items-center border-b border-slate-800 pb-3">
        <div>
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 animate-pulse" />
            Autonomous AI Document Watcher & Project Classifier Engine
          </h3>
          <p className="text-[11px] text-slate-400">
            Auto-detects title blocks, location stamps (Gurugram vs Andaman), client brands (Tanishq / Nestle / Amul) & routes drawings automatically
          </p>
        </div>
        <span className="text-[10px] text-cyan-300 font-mono bg-cyan-950 px-2.5 py-1 rounded-full border border-cyan-800 font-bold">
          OCR & Multimodal Title Block Vision Active
        </span>
      </div>

      {/* Preset Test Drawing Drops */}
      <div className="space-y-2">
        <span className="text-xs font-semibold text-slate-300 block">Simulate Dropping Client Drawings / Blueprints:</span>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-xs">
          {sampleDrawingFiles.map((file, idx) => (
            <button
              key={idx}
              onClick={() => handleProcessFile(file)}
              className="p-3 bg-slate-950 hover:bg-slate-800/80 border border-slate-800 rounded-xl text-left transition space-y-1 group"
            >
              <div className="flex items-center space-x-2 text-cyan-400 font-bold group-hover:text-white">
                <span>📄</span>
                <span className="truncate text-[11px]">{file.filename}</span>
              </div>
              <span className="text-[10px] text-slate-400 block">{file.description}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Live AI Classification Stream Result */}
      {isProcessing && (
        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-xs text-center space-y-2 py-6">
          <span className="w-4 h-4 rounded-full border-2 border-cyan-400 border-t-transparent animate-spin inline-block" />
          <p className="text-cyan-300 font-bold">AI Reading Title Block Metadata, Client Brand Tags & Location Coordinates...</p>
        </div>
      )}

      {latestClassification && !isProcessing && (
        <div className="bg-slate-950 border border-cyan-500/30 rounded-2xl p-4 space-y-3 animate-fade-in">
          <div className="flex justify-between items-center border-b border-slate-800 pb-2">
            <div>
              <span className="text-[10px] text-slate-400 block font-mono">Scanned File: {latestClassification.filename}</span>
              <h4 className="text-sm font-bold text-white flex items-center gap-2 mt-0.5">
                <span>{latestClassification.isNewProject ? '🆕 Auto-Instantiated New Project Card' : '🎯 Auto-Matched Active Project'}</span>
              </h4>
            </div>
            <div className="text-right">
              <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-950 px-3 py-1 rounded-lg border border-emerald-800 block">
                {latestClassification.confidenceScore}% Match Confidence
              </span>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2 text-xs">
            <div className="bg-slate-900 p-2.5 rounded-xl border border-slate-800">
              <span className="text-[10px] text-slate-400 block">Detected Location</span>
              <span className="font-bold text-cyan-300">{latestClassification.parsedMetadata.location}</span>
            </div>

            <div className="bg-slate-900 p-2.5 rounded-xl border border-slate-800">
              <span className="text-[10px] text-slate-400 block">Detected Client Brand</span>
              <span className="font-bold text-pink-300">{latestClassification.parsedMetadata.client}</span>
            </div>

            <div className="bg-slate-900 p-2.5 rounded-xl border border-slate-800">
              <span className="text-[10px] text-slate-400 block">Detected Building Typology</span>
              <span className="font-bold text-amber-300">{latestClassification.parsedMetadata.buildingType}</span>
            </div>
          </div>

          <p className="text-[11px] text-slate-300 bg-slate-900/60 p-2.5 rounded-xl border border-slate-800">
            🤖 <strong>AI Autonomous Reasoning:</strong> {latestClassification.reasoning}
          </p>

          <button
            onClick={handleRouteToProject}
            className="w-full py-2.5 bg-gradient-to-r from-cyan-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 text-white font-extrabold text-xs rounded-xl shadow-lg shadow-cyan-600/30 transition transform hover:scale-[1.01]"
          >
            🚀 Open Project Workbench for '{latestClassification.matchedProjectTitle}'
          </button>
        </div>
      )}
    </div>
  );
}
